// Code generated by "stringer -type ProcessState"; DO NOT EDIT.

package main

import "strconv"

const _ProcessState_name = "StoppedStartingRunningError"

var _ProcessState_index = [...]uint8{0, 7, 15, 22, 27}

func (i ProcessState) String() string {
	if i < 0 || i >= ProcessState(len(_ProcessState_index)-1) {
		return "ProcessState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ProcessState_name[_ProcessState_index[i]:_ProcessState_index[i+1]]
}
